dist: xenial
sudo: required
env:
  global:
    - DOCKER_REPO=dockerpirate/aria2 
    - ALPINE_M=3
    - ALPINE_P=16
    - ARIA_M=1.36.0
    - ARIA_P=r1
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
script: bash ci.sh
